# 1. Use Java 18 base image
FROM eclipse-temurin:18-jdk

# 2. Install Tomcat 10 manually
RUN apt-get update && \
    apt-get install -y wget unzip && \
    wget https://downloads.apache.org/tomcat/tomcat-10/v10.1.24/bin/apache-tomcat-10.1.24.zip && \
    unzip apache-tomcat-10.1.24.zip && \
    mv apache-tomcat-10.1.24 /opt/tomcat && \
    rm apache-tomcat-10.1.24.zip

# 3. Remove default webapps
RUN rm -rf /opt/tomcat/webapps/*

# 4. Add your WAR file as ROOT
COPY ROOT.war /opt/tomcat/webapps/ROOT.war

# 5. Expose port 8080
EXPOSE 8080

# 6. Run Tomcat
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
